#!/usr/bin/env python3
"""
Stage, commit, push, and create PR for Multi-Agent Routing pattern.
Writes result to git_mar_done.txt in the repo root.
"""
import subprocess
import os

REPO = '/Users/houchia/Dropbox/Mac/Desktop/prompt-deploy/production-llm-patterns-engine'
OUT = os.path.join(REPO, 'git_mar_done.txt')
BRANCH = 'publish/index-maintenance'  # current branch

files_to_add = [
    'CONTENT_CALENDAR.md',
    'README.md',
    'AI_REGISTRY.md',
    'patterns/orchestration/multi-agent-routing/',
]

commit_msg = """Add Multi-Agent Routing pattern (#31)

Full build pipeline: research, architecture, TypeScript + Python
implementations, 27-test suite (unit/failure-mode/integration),
6 benchmark scenarios, cost analysis, and ops guidance.

Key content:
- LLM classification router with confidence gating and fallback
- 6 failure modes (incl. silent misroute accumulation)
- Cost analysis: GPT-4o-mini-as-router saves $34/day at 100K req/day
- Benchmark: routing overhead ~0ms beyond extra API call
- Cites Berkeley/CMU MAST study (1600+ traces) and Anthropic multi-agent blog
- Progress checkbox marked in CONTENT_CALENDAR.md
- Navigation matrix link restored in root README.md

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"""

pr_body = """## Summary

- Adds the complete **Multi-Agent Routing** pattern (#31, Sprint 8)
- Full TypeScript implementation (`src/ts/`) and idiomatic Python port (`src/py/`)
- 27-test suite: unit, failure mode (one per FM in README), and integration tests
- 6-scenario benchmark suite (happy-path, fallback, timeout, registry scale, concurrency, threshold sensitivity)
- Cost analysis with break-even calculations for same-model vs. cheaper-routing-model scenarios

## Key design decisions

- LLM classification with few-shot capability registry: generalizes to novel request phrasing
- Confidence gating with configurable threshold (default 0.75): low-confidence requests fall back rather than misrouting
- Fallback agent support: unclassifiable requests get a safe default path instead of an error
- Audit log on every decision: routing distribution shifts are measurable, enabling silent degradation detection
- Routing timeout: classification call failure doesn't block the entire pipeline

## Key findings

1. **Routing overhead is negligible** — the router adds ~0ms pure JS/Python overhead beyond the extra LLM classification call
2. **Use a cheaper model for routing** — GPT-4o-mini routing + GPT-4o agents saves ~$34/day at 100K req/day vs. routing with GPT-4o
3. **Threshold calibration matters** — moving threshold from 0.75→0.85 doubles fallback rate on a typical confidence distribution
4. **Silent misroute accumulation is the main failure mode** — routing distribution shifts over months without triggering alerts; audit log stats catch it

## Files changed

- `patterns/orchestration/multi-agent-routing/README.md` — Full pattern documentation
- `patterns/orchestration/multi-agent-routing/src/ts/` — TypeScript implementation + tests
- `patterns/orchestration/multi-agent-routing/src/py/` — Python implementation + tests
- `patterns/orchestration/multi-agent-routing/benchmarks/` — bench.ts, bench.py, scenarios.md, results.md
- `patterns/orchestration/multi-agent-routing/cost-analysis.md` — Pricing projections at 1K/10K/100K req/day
- `CONTENT_CALENDAR.md` — Marked Multi-Agent Routing as complete
- `README.md` — Restored navigation matrix hyperlink
- `AI_REGISTRY.md` — Updated status to Complete, updated counts

## Test plan

- [ ] TypeScript tests: `cd patterns/orchestration/multi-agent-routing/src/ts && npm install && npm test`
- [ ] Python tests: `cd patterns/orchestration/multi-agent-routing/src/py && pip install -e ".[dev]" && pytest`
- [ ] TypeScript benchmarks: `cd patterns/orchestration/multi-agent-routing/benchmarks && npx tsx bench.ts`
- [ ] Python benchmarks: `python patterns/orchestration/multi-agent-routing/benchmarks/bench.py`

## Notes

- OpenAI verification (Step 2.5 + post-pipeline) was skipped — OpenAI API not reachable from the build sandbox
- Run tests locally before merging

🤖 Generated by nightly-build-and-port scheduled task with [Claude Code](https://claude.com/claude-code)"""


def run(cmd, **kwargs):
    return subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, **kwargs)


with open(OUT, 'w') as f:
    # Stage files
    r = run(['git', 'add'] + files_to_add)
    f.write(f"git add: rc={r.returncode} {r.stderr}\n")
    if r.returncode != 0:
        f.write("FAILED at git add\n")
        raise SystemExit(1)

    # Commit
    r = run(['git', 'commit', '-m', commit_msg])
    f.write(f"git commit: rc={r.returncode}\n{r.stdout}\n{r.stderr}\n")
    if r.returncode != 0:
        f.write("FAILED at git commit\n")
        raise SystemExit(1)

    # Log
    r = run(['git', 'log', '--oneline', '-3'])
    f.write(f"log:\n{r.stdout}\n")

    # Push
    r = run(['git', 'push', 'origin', BRANCH])
    f.write(f"push: rc={r.returncode}\n{r.stdout}\n{r.stderr}\n")
    if r.returncode != 0:
        f.write(f"FAILED at git push\n")
        raise SystemExit(1)

    # Create PR
    r = run(['gh', 'pr', 'create',
             '--title', 'Add Multi-Agent Routing pattern (#31)',
             '--body', pr_body,
             '--base', 'main',
             '--head', BRANCH])
    f.write(f"gh pr create: rc={r.returncode}\n{r.stdout}\n{r.stderr}\n")
    f.write("DONE\n")
