#!/usr/bin/env python3
"""
Stage, commit, push, and create PR for Index Maintenance + Multi-Agent Routing.
Writes result to git_done.txt in the repo root.
"""
import subprocess
import os

REPO = '/Users/houchia/Dropbox/Mac/Desktop/prompt-deploy/production-llm-patterns-engine'
OUT = os.path.join(REPO, 'git_done.txt')
BRANCH = 'publish/index-maintenance'

files_to_add = [
    'CONTENT_CALENDAR.md',
    'README.md',
    'AI_REGISTRY.md',
    'patterns/data-pipeline/index-maintenance/',
    'patterns/orchestration/multi-agent-routing/',
]

commit_msg = """Publish: Index Maintenance + Multi-Agent Routing patterns (#30, #31)

Index Maintenance (#30, Sprint 8, data-pipeline):
- TypeScript + Python implementations with tiered maintenance scheduling
- 5 benchmark scenarios, cost analysis, ops guidance
- Marks CONTENT_CALENDAR.md checkbox

Multi-Agent Routing (#31, Sprint 8, orchestration):
- LLM classification router with confidence gating and fallback
- TypeScript + Python, 27 tests (unit/failure-mode/integration)
- 6 benchmark scenarios, cost analysis
- Cites Berkeley/CMU MAST study (1600+ traces) and Anthropic multi-agent blog
- Silent misroute accumulation documented as primary silent degradation FM
- Cost finding: GPT-4o-mini routing saves ~$34/day at 100K req/day

Updates CONTENT_CALENDAR.md, root navigation matrix, AI_REGISTRY.md.

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"""

pr_body = """## Summary

Two patterns from Sprint 8 built and ported by nightly-build-and-port scheduled task:

### Pattern #30: Index Maintenance (data-pipeline)
- TypeScript + Python implementations with tiered maintenance scheduling
- 5 benchmark scenarios + cost analysis

### Pattern #31: Multi-Agent Routing (orchestration)
- LLM classification router with confidence gating, fallback, and audit log
- TypeScript + Python, 27 tests (unit/failure-mode/integration)
- 6-scenario benchmark suite: happy-path overhead, fallback latency, routing timeout, registry scale, concurrency, threshold sensitivity
- Cost finding: GPT-4o-mini as routing model saves ~$34/day at 100K req/day vs. no routing

## Key design decisions (Multi-Agent Routing)

- LLM classification with few-shot capability registry
- Confidence gating with configurable threshold (default 0.75)
- Fallback agent support for low-confidence and timeout paths
- Per-request audit log: enables retrospective misroute analysis and distribution monitoring
- Silent misroute accumulation is the primary long-term failure mode

## Test plan

- [ ] Index Maintenance TS: `cd patterns/data-pipeline/index-maintenance/src/ts && npm install && npm test`
- [ ] Index Maintenance Py: `cd patterns/data-pipeline/index-maintenance/src/py && pip install -e '.[dev]' && pytest`
- [ ] Multi-Agent Routing TS: `cd patterns/orchestration/multi-agent-routing/src/ts && npm install && npm test`
- [ ] Multi-Agent Routing Py: `cd patterns/orchestration/multi-agent-routing/src/py && pip install -e '.[dev]' && pytest`

## Notes

- OpenAI verification was skipped (network not available in build sandbox)
- Run tests locally before merging

\U0001f916 Generated by nightly-build-and-port scheduled task with [Claude Code](https://claude.com/claude-code)"""


def run(cmd, **kwargs):
    return subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, timeout=60, **kwargs)


with open(OUT, 'w') as f:
    # Stage files
    r = run(['git', 'add'] + files_to_add)
    f.write(f"git add: rc={r.returncode} {r.stderr}\n")
    if r.returncode != 0:
        f.write("FAILED at git add\n")
        raise SystemExit(1)

    # Commit
    r = run(['git', 'commit', '-m', commit_msg])
    f.write(f"git commit: rc={r.returncode}\n{r.stdout}\n{r.stderr}\n")
    if r.returncode != 0:
        f.write("FAILED at git commit\n")
        raise SystemExit(1)

    # Log
    r = run(['git', 'log', '--oneline', '-3'])
    f.write(f"log:\n{r.stdout}\n")

    # Push
    r = run(['git', 'push', 'origin', BRANCH])
    f.write(f"push: rc={r.returncode}\n{r.stdout}\n{r.stderr}\n")
    if r.returncode != 0:
        f.write(f"FAILED at git push\n")
        raise SystemExit(1)

    # Create PR
    r = run(['gh', 'pr', 'create',
             '--title', 'Publish: Index Maintenance + Multi-Agent Routing patterns (#30, #31)',
             '--body', pr_body,
             '--base', 'main',
             '--head', BRANCH])
    f.write(f"gh pr create: rc={r.returncode}\n{r.stdout}\n{r.stderr}\n")
    f.write("DONE\n")
