#!/bin/bash
# Run this script to commit and push the nightly build results.
# Two patterns were built: Index Maintenance (already staged) and Multi-Agent Routing (new this session).
set -e
cd /Users/houchia/Dropbox/Mac/Desktop/prompt-deploy/production-llm-patterns-engine

# Stage all pattern files (index-maintenance may already be staged; -A re-stages any modifications)
git add CONTENT_CALENDAR.md README.md AI_REGISTRY.md
git add patterns/data-pipeline/index-maintenance/
git add patterns/orchestration/multi-agent-routing/

git commit -m "Publish: Index Maintenance + Multi-Agent Routing patterns (#30, #31)

Index Maintenance (#30, Sprint 8, data-pipeline):
- TypeScript + Python implementations with tiered maintenance scheduling
- 5 benchmark scenarios, cost analysis, ops guidance
- Marks CONTENT_CALENDAR.md checkbox

Multi-Agent Routing (#31, Sprint 8, orchestration):
- LLM classification router with confidence gating and fallback
- TypeScript + Python, 27 tests (unit/failure-mode/integration)
- 6 benchmark scenarios, cost analysis
- Cites Berkeley/CMU MAST study (1600+ traces) and Anthropic multi-agent blog
- Silent misroute accumulation documented as primary silent degradation FM
- Cost finding: GPT-4o-mini routing saves ~\$34/day at 100K req/day

Updates CONTENT_CALENDAR.md, root navigation matrix, AI_REGISTRY.md.

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"

echo "COMMIT_DONE: $(git log --oneline -1)"

git push origin publish/index-maintenance

gh pr create \
  --title "Publish: Index Maintenance + Multi-Agent Routing patterns (#30, #31)" \
  --base main \
  --head publish/index-maintenance \
  --body "## Summary

Two patterns from Sprint 8 built and ported by nightly-build-and-port scheduled task:

### Pattern #30: Index Maintenance (data-pipeline)
- TypeScript + Python implementations with tiered maintenance scheduling
- 5 benchmark scenarios + cost analysis

### Pattern #31: Multi-Agent Routing (orchestration)
- LLM classification router with confidence gating, fallback, and audit log
- TypeScript + Python, 27 tests (unit/failure-mode/integration)
- 6 benchmark scenarios: happy-path overhead, fallback latency, routing timeout, registry scale, concurrency, threshold sensitivity
- Cost finding: GPT-4o-mini as routing model saves ~$34/day at 100K req/day vs. no routing

## Key design decisions (Multi-Agent Routing)

- LLM classification with few-shot capability registry
- Confidence gating with configurable threshold (default 0.75)
- Fallback agent support for low-confidence and timeout paths
- Per-request audit log: enables retrospective misroute analysis and distribution monitoring
- Silent misroute accumulation is the primary long-term failure mode

## Test plan

- [ ] Index Maintenance TS: \`cd patterns/data-pipeline/index-maintenance/src/ts && npm install && npm test\`
- [ ] Index Maintenance Py: \`cd patterns/data-pipeline/index-maintenance/src/py && pip install -e '.[dev]' && pytest\`
- [ ] Multi-Agent Routing TS: \`cd patterns/orchestration/multi-agent-routing/src/ts && npm install && npm test\`
- [ ] Multi-Agent Routing Py: \`cd patterns/orchestration/multi-agent-routing/src/py && pip install -e '.[dev]' && pytest\`

## Notes

- OpenAI verification was skipped (network not available in build sandbox)
- Run tests locally before merging

🤖 Generated by nightly-build-and-port scheduled task"

echo "PR_DONE"
